import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PageWrapper, MenuSelector, AuthorProfile } from "@/components/common";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "James Nextjs Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/atom-one-dark.css"
        />
      </head>
      <body className={inter.className}>
        <PageWrapper>
          <AuthorProfile />
          <section className="h-100 border-test w-full flex-col items-center justify-center px-5">
            <MenuSelector />
            {children}
          </section>
        </PageWrapper>
      </body>
    </html>
  );
}
